globalThis.process ??= {}; globalThis.process.env ??= {};
import { c as createAstro, a as createComponent, m as maybeRenderHead, d as addAttribute, b as renderTemplate } from './astro/server_DBcCZzNC.mjs';
import { w as withBase } from './urls_Bz0TJc3Q.mjs';

const $$Astro = createAstro("https://rivaldy-portfolio.pages.dev");
const $$PostForm = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$PostForm;
  const { mode, collections, post } = Astro2.props;
  const isUpdate = mode === "update" && post;
  return renderTemplate`${maybeRenderHead()}<form${addAttribute(withBase("api/admin/posts"), "action")} method="post" enctype="multipart/form-data" data-optimize-images class="space-y-5"> <input type="hidden" name="action"${addAttribute(mode, "value")}> ${isUpdate && renderTemplate`<input type="hidden" name="id"${addAttribute(post.id, "value")}>`} <div class="grid gap-4 md:grid-cols-2"> <label class="block"> <span class="text-sm font-medium text-zinc-800">Title</span> <input name="title" type="text"${addAttribute(post?.title || "", "value")} required class="mt-2 w-full rounded-md border border-zinc-300 px-4 py-3 text-base outline-none focus:border-zinc-900"> </label> <label class="block"> <span class="text-sm font-medium text-zinc-800">Collections</span> <select name="collections" multiple required class="mt-2 min-h-28 w-full rounded-md border border-zinc-300 bg-white px-4 py-3 text-base outline-none focus:border-zinc-900"> ${collections.map((collection) => renderTemplate`<option${addAttribute(collection.id, "value")}${addAttribute(post?.collections.includes(collection.id), "selected")}> ${collection.name} </option>`)} </select> </label> </div> <label class="block"> <span class="text-sm font-medium text-zinc-800">Description</span> <textarea name="description" rows="4" class="mt-2 w-full rounded-md border border-zinc-300 px-4 py-3 text-base outline-none focus:border-zinc-900">${post?.description || ""}</textarea> </label> ${isUpdate && renderTemplate`<div> <p class="mb-2 text-sm font-medium text-zinc-800">Current Images</p> <div class="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5"> ${post.allImages.map((imagePath) => renderTemplate`<div class="rounded-md border border-zinc-200 p-2"> <img${addAttribute(withBase(imagePath), "src")}${addAttribute(post.title, "alt")} class="aspect-square w-full rounded object-cover" loading="lazy"> <label class="mt-2 flex items-center gap-2 text-xs text-zinc-700"> <input type="radio" name="selectedThumbnail"${addAttribute(imagePath, "value")}${addAttribute(imagePath === post.thumbnail, "checked")} class="accent-zinc-950">
Thumbnail
</label> <label class="mt-2 flex items-center gap-2 text-xs text-red-700"> <input type="checkbox" name="removeImages"${addAttribute(imagePath, "value")} class="accent-red-700">
Delete image
</label> </div>`)} </div> </div>`} <div class="grid gap-4 md:grid-cols-2"> <label class="block"> <span class="text-sm font-medium text-zinc-800"> ${isUpdate ? "Replace thumbnail" : "Thumbnail"} </span> <input name="thumbnail" type="file" accept="image/jpeg,image/png,image/webp"${addAttribute(!isUpdate, "required")} class="mt-2 w-full rounded-md border border-dashed border-zinc-300 px-4 py-5 text-sm file:mr-4 file:rounded-md file:border-0 file:bg-zinc-950 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white"> </label> <label class="block"> <span class="text-sm font-medium text-zinc-800">${isUpdate ? "Add images" : "Images"}</span> <input name="images" type="file" accept="image/jpeg,image/png,image/webp" multiple class="mt-2 w-full rounded-md border border-dashed border-zinc-300 px-4 py-5 text-sm file:mr-4 file:rounded-md file:border-0 file:bg-zinc-950 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white"> </label> </div> <div class="flex flex-wrap items-center gap-3"> <label class="flex items-center gap-3 rounded-md border border-zinc-200 px-4 py-3"> <input name="featured" type="checkbox"${addAttribute(post?.isFeatured, "checked")} class="h-5 w-5 accent-zinc-950"> <span class="text-sm font-medium text-zinc-800">Featured</span> </label> <button type="submit" class="ml-auto rounded-md bg-zinc-950 px-5 py-3 text-sm font-semibold text-white"> ${isUpdate ? "Save Post" : "Create Post"} </button> ${isUpdate && renderTemplate`<button type="submit" name="action" value="delete" class="rounded-md border border-red-200 px-5 py-3 text-sm font-medium text-red-700">
Delete Post
</button>`} </div> </form>`;
}, "/home/runner/work/rivaldy-portofolio/rivaldy-portofolio/src/components/admin/PostForm.astro", void 0);

export { $$PostForm as $ };
