globalThis.process ??= {}; globalThis.process.env ??= {};
import { c as createAstro, a as createComponent, m as maybeRenderHead, d as addAttribute, b as renderTemplate } from './astro/server_DBcCZzNC.mjs';
import { w as withBase } from './urls_Bz0TJc3Q.mjs';

const $$Astro = createAstro("https://rivaldy-portfolio.pages.dev");
const $$PricelistForm = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$PricelistForm;
  const { mode, pkg } = Astro2.props;
  const isUpdate = mode === "update" && pkg;
  return renderTemplate`${maybeRenderHead()}<form${addAttribute(withBase("api/admin/pricelist"), "action")} method="post" class="space-y-5"> <input type="hidden" name="action"${addAttribute(mode, "value")}> ${isUpdate && renderTemplate`<input type="hidden" name="originalId"${addAttribute(pkg.id, "value")}>`} <div class="grid gap-4 md:grid-cols-2"> <label class="block"> <span class="text-sm font-medium text-zinc-800">Package ID</span> <input name="id" type="text"${addAttribute(pkg?.id || "", "value")} placeholder="basic" class="mt-2 w-full rounded-md border border-zinc-300 px-4 py-3 text-base outline-none focus:border-zinc-900"> </label> <label class="block"> <span class="text-sm font-medium text-zinc-800">Package Name</span> <input name="name" type="text"${addAttribute(pkg?.name || "", "value")} required class="mt-2 w-full rounded-md border border-zinc-300 px-4 py-3 text-base outline-none focus:border-zinc-900"> </label> </div> <div class="grid gap-4 md:grid-cols-2"> <label class="block"> <span class="text-sm font-medium text-zinc-800">Price</span> <input name="price" type="text"${addAttribute(pkg?.price || "", "value")} placeholder="275K" required class="mt-2 w-full rounded-md border border-zinc-300 px-4 py-3 text-base outline-none focus:border-zinc-900"> </label> <label class="block"> <span class="text-sm font-medium text-zinc-800">Sort Order</span> <input name="sortOrder" type="number"${addAttribute(pkg?.sortOrder ?? 0, "value")} class="mt-2 w-full rounded-md border border-zinc-300 px-4 py-3 text-base outline-none focus:border-zinc-900"> </label> </div> <label class="block"> <span class="text-sm font-medium text-zinc-800">Features</span> <textarea name="features" rows="8" placeholder="Tulis satu fitur per baris" required class="mt-2 w-full rounded-md border border-zinc-300 px-4 py-3 text-base outline-none focus:border-zinc-900">${pkg?.features.join("\n") || ""}</textarea> </label> <div class="flex flex-wrap items-center gap-3"> <label class="flex items-center gap-3 rounded-md border border-zinc-200 px-4 py-3"> <input name="enabled" type="checkbox"${addAttribute(pkg?.enabled ?? true, "checked")} class="h-5 w-5 accent-zinc-950"> <span class="text-sm font-medium text-zinc-800">Show Package</span> </label> <label class="flex items-center gap-3 rounded-md border border-zinc-200 px-4 py-3"> <input name="popular" type="checkbox"${addAttribute(pkg?.popular ?? false, "checked")} class="h-5 w-5 accent-zinc-950"> <span class="text-sm font-medium text-zinc-800">Popular</span> </label> <button type="submit" class="ml-auto rounded-md bg-zinc-950 px-5 py-3 text-sm font-semibold text-white"> ${isUpdate ? "Save Package" : "Create Package"} </button> ${isUpdate && renderTemplate`<button type="submit" name="action" value="delete" class="rounded-md border border-red-200 px-5 py-3 text-sm font-medium text-red-700">
Delete Package
</button>`} </div> </form>`;
}, "/home/runner/work/rivaldy-portofolio/rivaldy-portofolio/src/components/admin/PricelistForm.astro", void 0);

export { $$PricelistForm as $ };
